name: Infrastructure deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-infra.yml'
      - 'infrastructure/**'
  workflow_dispatch:

env:
  LOCATION: "norwayeast"

permissions:
  id-token: write
  contents: read

jobs:
  bicep-whatif:
    name: Bicep What-if
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Bicep lint
        uses: Azure/cli@v2
        with:
          inlinescript: az bicep build --file infrastructure/main.bicep

      - name: Bicep validate
        uses: Azure/cli@v2
        with:
          inlinescript: |
            az deployment sub validate \
            --name validate-${{ github.run_id }} \
            --template-file infrastructure/main.bicep \
            --location $LOCATION

      - name: "What-If"
        uses: Azure/cli@v2
        with:
          inlinescript: |
            az deployment sub what-if \
            --name whatif-${{ github.run_id }} \
            --template-file infrastructure/main.bicep \
            --location $LOCATION
