name: Infrastructure deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-infra.yml'
      - 'infrastructure/**'
  workflow_dispatch:

env:
  subscription: 'Visual Studio Enterprise Subscription – MPN'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlinescript: |
            az account show
