# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - snek-game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Generate EF migration script
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations script --idempotent --no-build --configuration Release --project ./Snek/Snek/Snek.csproj --output ${{env.DOTNET_ROOT}}/migrations.sql --verbose

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/snek-app

      - name: Upload EF migration script artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dbmigrationscript
          path: ${{env.DOTNET_ROOT}}/migrations.sql

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: snekapp
          path: ${{env.DOTNET_ROOT}}/snek-app

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: snekapp 

      - name: Download EF migration script artifact from build job
        id: download-migration-script
        uses: actions/download-artifact@v3
        with:
          name: dbmigrationscript

      - name: Update DB using SQL script
        uses: azure/sql-action@v2.2
        with:
          connection-string: ${{ secrets.DB_CONNECTION_STRING }}
          path: ${{ steps.download-migration-script.outputs.download-path }}/migrations.sql
          action: "publish"

      - name: App settings variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "${{ steps.download-artifact.outputs.download-path }}/appsettings.json"
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'snek-game'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1FB9D4E4837244188F886E967968C2C2 }}
          package: .
